# Generated by Django 2.2.16 on 2022-07-20 14:25

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('reviews', '0011_auto_20220720_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenresTitles',
            new_name='GenreTitles',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='genretitles',
            options={'verbose_name': 'Произведение и жанр', 'verbose_name_plural': 'Произведения и жанры'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
